name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "42ac523fa25cc84e07a297cec334af8a"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "pb.bingshuang.club", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "03968665b8834b979b9f9ea21ca329bd" },
  { binding = "PBIMGS", id ="2cbacce6c8c84e0893547b5bf66c3ced" }
]

[site]
bucket = "./static/dist"
